language: java

after_success:
  - ls -l;
  - cd target ;
  - ls -l;
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force "https://${GHTOKEN}@${GH_REF}" master:gh-pages
