# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
 push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Deploy to local repo
    - name: Deploy to gh-pages
      run: |
        cd target/generated-docs
        mv handbuch.html index.html
        git init
        git config --global user.email "ghactions@github.com"
        git config --global user.name "Deploy Agent"
        git add .
        git commit -m "deploy to gh pages"
        git status
        git push --force https://FrankR85:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY master:gh-pages
        

