# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
 push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      actions: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        rm -rf ghpages/
        mvn -B package --file pom.xml
        cp -r target/generated-docs/ ghpages/
        mv ghpages/handbuch.html ghpages/index.html
        
    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ghpages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

